//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by Buttons.rc
//
#define DLG_CONFIG                      104
#define IDB_BITMAP1                     108
#define IDC_USEMIRRORS                  1001
#define IDC_TRINKETS                    1011
#define IDC_CLASSIC                     1012
#define IDC_PHOTOS                      1013

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        110
#define _APS_NEXT_COMMAND_VALUE         40001
#define _APS_NEXT_CONTROL_VALUE         1012
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
